name: Build pipa images
on:
  push: # Build when push
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * 5' # Start build every friday

jobs:
  build-image:
    strategy:
      matrix:
        version: ["default"]

    runs-on: ubuntu-latest
    steps:
      - name: Check out build configurations
        uses: actions/checkout@v4
        
      - name: Create artifact directory
        run: |
            mkdir out
        
      - name: Substitute placeholders in configs
        run: |
           find . -type f -name "*.cfg" -exec sed -i "s|HOME|$(echo $HOME)|;s|NPROC|$(nproc)|" {} +

      - name: Install pmbootstrap from git
        run: |
          git clone --depth=1 https://gitlab.postmarketos.org/postmarketOS/pmbootstrap.git
          mkdir -p ~/.local/bin
          ln -s "$PWD/pmbootstrap/pmbootstrap.py" ~/.local/bin/pmbootstrap
          pmbootstrap --version

      - name: Set up pmaports
        run: |
          echo -e '\n\n' | pmbootstrap init || true
          cd ~/.local/var/pmbootstrap/cache_git/pmaports
          git remote
          git remote add pipa https://github.com/pipa-project/pmaports-pipa.git
          DEFAULT_BRANCH=$(git remote show pipa | awk '/HEAD branch/ {print $NF}')
          git fetch pipa $DEFAULT_BRANCH
          git reset --hard pipa/$DEFAULT_BRANCH

      - name: Build the xiaomi-pipa with Phosh and FDE
        run: |
           cp xiaomi-pipa.cfg ~/.config/pmbootstrap_v3.cfg
           pmbootstrap install --password 147147 --fde --add postmarketos-ui-phosh
           pmbootstrap export
           cp /tmp/postmarketOS-export/boot.img out/boot-xiaomi-pipa.img
           cp /tmp/postmarketOS-export/xiaomi-pipa.img out/rootfs-xiaomi-pipa-phosh-fde.img
        env:
          PMB_FDE_PASSWORD: ${{ secrets.PMB_FDE_PASSWORD }}

      - name: Breakpoint if tests failed for xiaomi-pipa without DE
        if: failure()
        uses: namespacelabs/breakpoint-action@v0
        with:
          duration: 30m
          authorized-users: milikhin
      
      - name: Upload artifacts xiaomi-pipa with FDE and Phosh
        uses: actions/upload-artifact@v4
        with:
           name: xiaomi-pipa-phosh-fde
           path: out/*.img*
           retention-days: 7

      - name: Build the xiaomi-pipa with Phosh
        run: |
           yes | pmbootstrap zap
           rm -r out/*
           pmbootstrap install --password 147147 --add postmarketos-ui-phosh
           cat /home/runner/.local/var/pmbootstrap/log.txt
           pmbootstrap export
           cp /tmp/postmarketOS-export/boot.img out/boot-xiaomi-pipa.img
           cp /tmp/postmarketOS-export/xiaomi-pipa.img out/rootfs-xiaomi-pipa-phosh.img

      - name: Breakpoint if tests failed for xiaomi-pipa with Phosh
        if: failure()
        uses: namespacelabs/breakpoint-action@v0
        with:
          duration: 30m
          authorized-users: milikhin
      
      - name: Upload artifacts xiaomi-pipa with Phosh
        uses: actions/upload-artifact@v4
        with:
           name: xiaomi-pipa-phosh
           path: out/*.img*
           retention-days: 7

      - name: Copy xiaomi-pipa kernel
        run: |
           rm -r out/*
           cp ~/.local/var/pmbootstrap/packages/edge/aarch64/linux-postmarketos-qcom-sm8250-pipa-*.apk out/
      
      - name: Upload artifacts xiaomi-pipa kernel
        uses: actions/upload-artifact@v4
        with:
           name: xiaomi-pipa-kernel
           path: out/*.apk
           retention-days: 7



        

        
